companion_animals/chat/urls.py
# chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("index", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:room_pk>/", views.enter_room, name="room"),
]

companion_animals/common/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "common"

urlpatterns = [
    # django.contrib.auth 에서 제공하는 LoginView
    # 클래스를 활용하기 때문에 별도의 views 는 작성하지 않음
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
    path("profile/", views.profile, name="profile"),
    path("member_del/", views.delete, name="delete"),
    path("change_password/", views.change_password, name="change_password"),
    # 비밀번호 초기화
    path(
        "password_reset/",
        views.PasswordResetView.as_view(template_name="common/password_reset.html"),
        name="password_reset",
    ),
    path(
        "password_reset_done/",
        views.PasswordResetDoneView.as_view(
            template_name="common/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="common/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
]

companion_animals/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from petmap import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("common/", include("common.urls")),
    path("petmap/", include("petmap.urls")),
    path("chat/", include("chat.urls")),
    # 메인화면
    path("", views.main, name="main"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

companion_animals/board/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q, Count
from ..models import Board, BoardCount
from tools.utils import get_client_ip


# 게시판 목록 조회
def index(request):
    # question 테이블 내용 조회
    # Question.objects.all()

    page = request.GET.get("page", 1)  # http://127.0.0.1:8000/board/?page=1
    keyword = request.GET.get("keyword", "")
    sort = request.GET.get("sort", "")
    sort2 = request.GET.get("sort2", "")
    sort_a = request.GET.get("sort_a", "recents")

    # annotate() : voter라는 필드의 개수를 센 후 nun_voter라는 임시 필드를 추가해 주는 함수
    if sort_a == "recents":
        board_list = Board.objects.order_by("-create_date")
    elif sort_a == "recommends":
        board_list = Board.objects.annotate(num_voter=Count("voter")).order_by(
            "-num_voter", "-create_date"
        )
    else:
        board_list = Board.objects.annotate(num_answer=Count("answer")).order_by(
            "-num_answer", "-create_date"
        )

    # 행정 구 에 맞게 소팅
    if sort == "서울전체":
        pass
    else:
        board_list = board_list.filter(Q(gu__contains=sort))

    # 카테고리에 맞게 소팅
    if sort2 == "분류없음":
        pass
    else:
        board_list = board_list.filter(Q(category__contains=sort2))

    # 조회된 목록을 기준으로 검색 조건을 줘서 필터링
    # Q() : OR 조건으로 데이터를 조회
    # subject__contains(대소문자 구별)
    # subject__icontains(대소문자 구별 하지 않음)

    if keyword:
        board_list = board_list.filter(
            Q(subject__icontains=keyword)
            | Q(content__icontains=keyword)
            | Q(nickname__nickname__icontains=keyword)
            | Q(answer__nickname__nickname__icontains=keyword)
        ).distinct()

    paginator = Paginator(
        board_list, 10
    )  # Paginator 객체 생성(전체목록, 10) : 전체목록에서 10개씩 가져오기
    page_obj = paginator.get_page(page)

    context = {
        "board_list": page_obj,
        "page": page,
        "keyword": keyword,
        "sort": sort,
        "sort_a": sort_a,
        "sort2": sort2,
    }

    return render(request, "board/board_list.html", context)


# 게시판 상세페이지
def detail(request, board_id):

    ### 페이지 나누기 추가
    page = request.GET.get("page", 1)  # http://127.0.0.1:8000/board/?page=1
    keyword = request.GET.get("keyword", "")
    sort = request.GET.get("sort", "")
    sort_a = request.GET.get("sort_a", "")

    # 없는 id를 요청했을 때 웹 페이지에 오류 메세지가 그대로 출력
    board = get_object_or_404(Board, id=board_id)

    ### 조회수 추가
    # 사용자 ip 가져오기
    ip = get_client_ip(request)

    # 찾은 ip가 BoardCount 테이블에 있는지 확인
    cnt = BoardCount.objects.filter(ip=ip, board=board).count()

    if cnt == 0:  # 조회수 증가
        # 모델 생성
        bc = BoardCount(ip=ip, board=board)
        # 저장
        bc.save()
        # question 테이블의 view_cnt 1 증가
        if board.view_cnt:
            board.view_cnt += 1
        else:
            board.view_cnt = 1
        board.save()
    context = {
        "board": board,
        "page": page,
        "keyword": keyword,
        "sort": sort,
        "sort_a": sort_a,
    }
    return render(request, "board/board_detail.html", context)

companion_animals/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href={% static 'css/bootstrap.min.css' %}/>
    <link rel="stylesheet" href={% static 'css/mystyle.css' %}/>
    <link rel="shortcut icon" href="#">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Black+And+White+Picture&family=Black+Han+Sans&family=Cute+Font&family=Do+Hyeon&family=Dokdo&family=East+Sea+Dokdo&family=Gaegu&family=Gamja+Flower&family=Gothic+A1&family=Gugi&family=Hi+Melody&family=Jua&family=Kirang+Haerang&family=Nanum+Brush+Script&family=Nanum+Gothic&family=Nanum+Gothic+Coding&family=Nanum+Myeongjo&family=Nanum+Pen+Script&family=Noto+Sans+KR&family=Noto+Serif+KR&family=Poor+Story&family=Single+Day&family=Song+Myung&family=Stylish&family=Sunflower:wght@300&family=Yeon+Sung&display=swap" rel="stylesheet">
    <title>장고 게시판</title>
  </head>
  <body style="background-color:#FBF8BE;">
    {% include 'navbar.html' %}
    <!-- 기본 템플릿 안에 삽입 시작 -->
    {% block content %}

    <!-- 각 페이지마다 다른 내용 작성-->
    {% endblock %}
    <script src={% static 'js/jquery-3.6.0.min.js' %}></script>
    <script src={% static 'js/bootstrap.min.js' %}></script>
    {% block script %}
      <!-- 페이지마다 서로 다른 스크립트 작성 영역 -->
    {% endblock %}
  </body>
</html>

companion_animals/templates/form_errors.html
<!-- 오류 표시 -->
{% if form.errors %} {% for field in form %}
<!-- form 안의 요소들 오류 출력 : 입력값 누락, 형식에 맞지 않는 경우-->
{% for error in field.errors %}
<div class="alert alert-danger" role="alert">
  <strong>{{field.label}}</strong>
  {{error}}
</div>
{% endfor %} {% endfor %} {% for error in field.non_field_errors %}
<!-- non_field_errors : 입력값과 관계없이 발생한 오류 -->
<div class="alert alert-danger" role="alert">
  <strong>{{error}}</strong>
</div>
{% endfor %} {% endif %}

companion_animals/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light border-bottom" style="background-color: #234e70">
  <a class="navbar-brand" href="{% url 'main' %}" style="color: white">Paws & Tails</a>
  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        {% if user.is_authenticated %}
        <div class="row">
          <a class="nav-link" href="{% url 'common:logout' %}" style="color: white">{{user.username}}님 로그아웃</a>
          <h3 style="color: #fbf8be">/</h3>
          <a class="nav-link" href="{% url 'common:profile' %}" style="color: white">프로필 보기</a>
          <h3 style="color: #fbf8be">/</h3>
          <a class="nav-link" href="{% url 'chat:index' %}" style="color: white">채팅방 입장하기</a>
        </div>
        {% else %}
        <div class="row">
          <a class="nav-link" href="{% url 'common:login' %}" style="color: white">로그인</a>
          <a class="nav-link" href="{% url 'common:signup' %}" style="color: white">회원가입</a>
        </div>
        {% endif %}
      </li>
    </ul>
  </div>
</nav>