companion_animals/chat/urls.py
# chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("index", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:room_pk>/", views.enter_room, name="room"),
]

companion_animals/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from petmap import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("common/", include("common.urls")),
    path("petmap/", include("petmap.urls")),
    path("chat/", include("chat.urls")),
    # 메인화면
    path("", views.main, name="main"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

companion_animals/chat/models.py
from django.db import models
from django.conf import settings

# 채팅방 목록을 구성하고, 누가 참여하고 있는지 데이터를 만들고 방이 파괴되거나 사람이 나가면 제거


class Room(models.Model):
    count_users = models.BigIntegerField(default=0)
    room_name = models.CharField(max_length=255)  # 채팅방 이름
    # subject = models.CharField(max_length=255) # 채팅방에 대한 간략한 설명


class Message(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    content = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("date_added",)


class RoomCount(models.Model):
    ip = models.CharField(max_length=30)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.ip

companion_animals/chat/views.py
# chat/views.py
from common.models import Profile
from time import time
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Room, RoomCount
from tools.utils import get_client_ip


def index(request):
    rooms = Room.objects.filter(count_users__lte=0)
    profile = Profile.objects.get(user_id=request.user)
    for room in rooms:
        try:
            time.sleep(1)
        except:
            pass
        room.delete()
    rooms = Room.objects.all()
    context = {
        "rooms": rooms,
        "profile": profile,
    }
    return render(request, "chat/index.html", context)


@login_required
def enter_room(request, room_pk):
    if request.user.is_authenticated:
        user = request.user
        room = Room.objects.get(pk=room_pk)
        profile = Profile.objects.get(user_id=request.user)

        ### 인원 추가
        # 사용자 ip 가져오기
        ip = get_client_ip(request)

        # 찾은 ip가 BoardCount 테이블에 있는지 확인
        cnt = RoomCount.objects.filter(ip=ip, room=room).count()

        if cnt == 0:  # 조회수 증가
            # 모델 생성
            rc = RoomCount(ip=ip, room=room)
            # 저장
            rc.save()
            # question 테이블의 view_cnt 1 증가
            if room.count_users:
                room.count_users += 1
            else:
                room.count_users = 1
            room.save()

        room.save()
        context = {
            "room": room,
            "user": user,
            "profile": profile,
        }
        return render(request, "chat/room.html", context)


@login_required
def create(request):
    if request.user.is_authenticated:
        room_name = request.POST["roomname"]
        room = Room.objects.create(room_name=room_name)
        return redirect("chat:room", room.pk)

companion_animals/templates/chat/index.html
{% extends 'base.html' %} {% block content %}
<div class="container row">
  <div class="section-title col-6 offset-3">
    <h4 class="mt-4">반려동물 채팅</h4>
    <h5 class="my-3">실시간으로 집사와 반려동물 이야기를 나눠보세요</h5>
  </div>
  <div class="row col-6 offset-3 my-3">
    <form action="{% url 'chat:create' %}" method="POST">
      {% csrf_token %}
      <div class="section-body col-6">
        <div class="field">
          <label>Room name</label>
          <div class="control">
            <input name="roomname" type="text" placeholder="채팅방 이름을 입력해주세요" id="room-name-input" size="40" />
          </div>
        </div>
        <!-- <div class="field">
                        <label>Username</label>
                            <div class="control">
                                <input name="username" type="text" placeholder="Username" id="username-input" name="user-name">
                            </div>
                    </div> -->
        <button type="submit" class="btn btn-secondary my-3">채팅방 생성하기</button>
      </div>
    </form>
  </div>
  <div class="col-6 offset-3">
    <hr />
    <h5>반려동물 이야기방</h5>
    <hr />
    <div>
      {% for room in rooms %}
      <div>{{ room.room_name }} <a href="{% url 'chat:room' room.pk %}">입장하기</a></div>
      <div>현재 참여 인원 : {{ room.count_users }}</div>
      {% endfor %}
    </div>
  </div>
</div>

{% endblock content %}

companion_animals/templates/chat/room.html
{% extends 'base.html' %} {% block content %}
<div class="m-5">
  <h5>방 이름: <span id="room-name" value="{{ room.pk }}" user="{{ profile.nickname }}">{{ room.room_name }}</span></h5>
  <h5>{{ profile.nickname }}님 반갑습니다.</h5>
  <textarea id="chat-log" cols="100" rows="20" readonly></textarea><br />
  <input id="chat-message-input" type="text" size="100" /><br />
  <input class="mt-3" id="chat-message-submit" type="button" value="입력하기" />
  <button id="chat-close"><a id="chat-close-btn" href="{% url 'chat:index' %}">채팅방 나가기</a></button>
</div>
{% endblock content %}
<!-- {{ room_name|json_script:"room-name" }} -->
{% block script %}
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<script>
  const roomId = document.getElementById("room-name").getAttribute("value");
  const username = document.querySelector("#room-name").getAttribute("user");

  // 클라이언트 쪽에서 서버와 통신할 웹소켓을 만들고
  // ws 프로토콜 사용(wss와 ws는 https와 http와의 관계와 유사)
  const chatSocket = new WebSocket("ws://" + window.location.host + "/ws/chat/" + roomId + "/");

  // 서버로부터 데이터 수신
  chatSocket.onmessage = function (e) {
    const data = JSON.parse(e.data);
    console.log(data);
    document.querySelector("#chat-log").value += data.username + " : ";
    document.querySelector("#chat-log").value += data.message + "\n";
  };

  // 연결 시도 중 에러가 발생하면, 먼저 'error'라는 이름의 이벤트가 WebSocket오브젝트로 전달
  // 그로 인해 onerror 핸들러 실행
  // 그 후에 연결이 종료되는 이유를 가리키는 closeevent가 WebSocket오브젝트로 전달되고
  // 그로 인해 onclose가 실행
  const chatClose = (document.querySelector("#chat-close").onclick = function (e) {
    chatSocket.close();
    console.log("채팅방이 닫힘");
  });

  chatSocket.onclose = function (e) {
    console.error("Chat socket closed unexpectedly");
  };

  document.querySelector("#chat-message-input").focus();
  document.querySelector("#chat-message-input").onkeyup = function (e) {
    if (e.keyCode === 13) {
      // enter, return
      document.querySelector("#chat-message-submit").click();
    }
  };

  // 서버에 데이터를 전송
  document.querySelector("#chat-message-submit").onclick = function (e) {
    const messageInputDom = document.querySelector("#chat-message-input");
    const message = messageInputDom.value;
    chatSocket.send(
      JSON.stringify({
        message: message,
        username: username,
      })
    );
    messageInputDom.value = "";
  };
</script>

<style>
  #chat-close-btn {
    text-decoration: none;
    color: black;
  }
</style>
{% endblock %}