companion_animals/board/urls.py
from .views import base_views, answer_views, comment_views, board_views, vote_views
from django.urls import path

# 네임스페이스 지정
app_name = "board"

urlpatterns = [
    # 게시물 목록 보여주기
    path("", base_views.index, name="index"),
    # 게시물 상세페이지 보여주기
    path("<int:board_id>", base_views.detail, name="detail"),
    # 게시물 등록
    path("board/create", board_views.board_create, name="board_create"),
    # 게시물 수정
    # /board/board/modify/ board_modify
    path(
        "board/modify/<int:board_id>",
        board_views.board_modify,
        name="board_modify",
    ),
    # 게시물 삭제
    # /board/board/delete/board_delete
    path(
        "board/delete/<int:board_id>",
        board_views.board_delete,
        name="board_delete",
    ),
    # 댓글 등록
    # /board/answer/create/1
    path(
        "answer/create<int:board_id>",
        answer_views.answer_create,
        name="answer_create",
    ),
    # 댓글 수정
    # /board/answer/modify/1 answer.id : 값을 받을 변수 answer_id
    path(
        "answer/modify/<int:answer_id>",
        answer_views.answer_modify,
        name="answer_modify",
    ),
    # 댓글 삭제
    # /board/answer/delete/1 answer.id : 값을 받을 변수 answer_id
    path(
        "answer/delete/<int:answer_id>",
        answer_views.answer_delete,
        name="answer_delete",
    ),
    # 대댓글 작성
    # /board/comment/create/answer_id
    path(
        "comment/create/<int:answer_id>",
        comment_views.comment_create,
        name="comment_create",
    ),
    # 대댓글 수정
    path(
        "comment/modify/<int:comment_id>",
        comment_views.comment_modify,
        name="comment_modify",
    ),
    # 대댓글 삭제
    path(
        "comment/delete/<int:comment_id>",
        comment_views.comment_delete,
        name="comment_delete",
    ),
    # 질문 추천 수
    path(
        "vote/board/<int:board_id>",
        vote_views.vote_board,
        name="vote_board",
    ),
]

companion_animals/chat/urls.py
# chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("index", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:room_pk>/", views.enter_room, name="room"),
]

companion_animals/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from petmap import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("common/", include("common.urls")),
    path("petmap/", include("petmap.urls")),
    path("chat/", include("chat.urls")),
    # 메인화면
    path("", views.main, name="main"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

companion_animals/board/models.py
from unicodedata import category
from django.db import models
from common.models import Profile
from django.contrib.auth.models import User

# 게시글
class Board(models.Model):
    # 구별
    gu = models.CharField(max_length=5)
    # 제목
    subject = models.CharField(max_length=200)
    # 내용
    content = models.TextField()
    # 작성자
    nickname = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="nickname_board"
    )
    # 카테고리
    category = models.CharField(max_length=20)
    # 생성 날짜
    create_date = models.DateTimeField()
    # 수정된 날짜 보여주기
    # black=True : form.is_valid()를 통한 폼 검사시 값이 없어도 됨
    update_date = models.DateTimeField(null=True, blank=True)
    # 추천수
    # ManyToManyField : 다대다
    voter = models.ManyToManyField(User, related_name="vote_board")
    # 조회수
    view_cnt = models.BigIntegerField(default=0)


# 댓글
class Answer(models.Model):
    # Answer 테이블과 Board 테이블의 외래키 제약 조건
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    # 댓글 내용
    content = models.TextField()
    # 작성자
    nickname = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="nickname_answer"
    )
    # 생성 날짜
    create_date = models.DateTimeField()
    # 수정된 날짜 보여주기
    # black=True : form.is_valid()를 통한 폼 검사시 값이 없어도 됨
    update_date = models.DateTimeField(null=True, blank=True)


# 대댓글
class Comment(models.Model):
    # Answer 테이블과 Board 테이블의 외래키 제약 조건
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    # 댓글 내용
    content = models.TextField()
    # 작성자
    nickname = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="nickname_comment"
    )
    # 생성 날짜
    create_date = models.DateTimeField()
    # 수정된 날짜 보여주기
    # black=True : form.is_valid()를 통한 폼 검사시 값이 없어도 됨
    update_date = models.DateTimeField(null=True, blank=True)


class BoardCount(models.Model):
    ip = models.CharField(max_length=30)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.ip

companion_animals/board/forms.py
from django import forms
from .models import Board, Answer, Comment

# ModelForm - 모델과 연결된 폼
# class Meta 반드시 가져야 함
class BoardForm(forms.ModelForm):
    class Meta:
        model = Board

        fields = ["subject", "gu", "content", "category"]
        # 에러 메세지가 보여질 때 라벨명이 field명을 이용하기 때문에
        # 영어로 나오는 부분을 원하는 한글로 변경
        labels = {"subject": "제목", "content": "내용", "gu": "행정 구", "category": "카테고리"}


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer

        fields = ["content"]

        # 에러 메세지가 보여질 때 라벨명이 field명을 이용하기 때문에
        # 영어로 나오는 부분을 원하는 한글로 변경
        labels = {"content": "답변 내용"}


# comment 테이블과 연결된 폼 : form.save() => db 반영
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment

        fields = ["content"]
        labels = {"content": "댓글 내용"}

companion_animals/board/views/answer_views.py
from django.shortcuts import redirect, render, get_object_or_404, resolve_url
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from common.models import Profile
from ..models import Board, Answer
from ..forms import AnswerForm

# 댓글 등록
@login_required(login_url="common:login")
def answer_create(request, board_id):
    # board_id 를 사용해 질문 가져오기
    board = Board.objects.get(id=board_id)

    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            # 작성자 추가 (현재 로그인 사용자 : request.user)
            profile = Profile.objects.get(user_id=request.user)
            answer.nickname = profile
            answer.create_date = timezone.now()
            answer.board = board
            answer.save()

            # detail에서 특정 영역 보여주기
            # http://1270.0.0.1:8000/board/305#answer_7
            return redirect(
                "{}#answer_{}".format(
                    # resolce_url() : 실제 호출되는 URL을 문자열로 반환
                    resolve_url("board:detail", board_id=board_id),
                    answer.id,
                )
            )
    else:
        form = AnswerForm()

    context = {"board": board, "form": form}

    return render(request, "board/board_detail.html", context)


# 답변 수정 - 원본 내용 찾은 후 수정
# 답변 수정 전에 로그인 확인 여부
@login_required(login_url="common:login")
def answer_modify(request, answer_id):
    # answer_id에 해당하는 데이터 가져오기
    answer = get_object_or_404(Answer, pk=answer_id)

    # 작성자와 같은지 확인
    if request.user.id == answer.nickname:
        messages.error(request, "수정할 권한이 없습니다.")
        return redirect("board:detail", board_id=answer.board.id)

    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)

        # 유효성 검사
        if form.is_valid():
            answer = form.save(commit=False)
            profile = Profile.objects.get(user_id=request.user)
            answer.nickname = profile
            answer.modify_date = timezone.now()  # 수정 날짜
            answer.save()

            # detail에서 특정 영역 보여주기
            # http://1270.0.0.1:8000/board/305#answer_7
            return redirect(
                # 앞 {} : 글 번호
                # 뒤 {} : answer.id
                "{}#answer_{}".format(
                    # resolce_url() : 실제 호출되는 URL을 문자열로 반환
                    resolve_url("board:detail", board_id=answer.board_id),
                    answer.id,
                )
            )

    else:
        form = AnswerForm(instance=answer)
    return render(request, "board/answer_form.html", {"form": form})


# 댓글 삭제
@login_required(login_url="common:login")
def answer_delete(request, answer_id):
    # 삭제할 데이터 찾기
    answer = get_object_or_404(Answer, pk=answer_id)

    # 작성자와 같은지 확인
    if request.user.id == answer.nickname:
        messages.error(request, "삭제할 권한이 없습니다.")
        return redirect("board:detail", board_id=answer.board.id)

    answer.delete()

    # 내용보기로 들어가기
    return redirect("board:detail", board_id=answer.board_id)

companion_animals/board/views/base_views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q, Count
from ..models import Board, BoardCount
from tools.utils import get_client_ip


# 게시판 목록 조회
def index(request):
    # question 테이블 내용 조회
    # Question.objects.all()

    page = request.GET.get("page", 1)  # http://127.0.0.1:8000/board/?page=1
    keyword = request.GET.get("keyword", "")
    sort = request.GET.get("sort", "")
    sort2 = request.GET.get("sort2", "")
    sort_a = request.GET.get("sort_a", "recents")

    # annotate() : voter라는 필드의 개수를 센 후 nun_voter라는 임시 필드를 추가해 주는 함수
    if sort_a == "recents":
        board_list = Board.objects.order_by("-create_date")
    elif sort_a == "recommends":
        board_list = Board.objects.annotate(num_voter=Count("voter")).order_by(
            "-num_voter", "-create_date"
        )
    else:
        board_list = Board.objects.annotate(num_answer=Count("answer")).order_by(
            "-num_answer", "-create_date"
        )

    # 행정 구 에 맞게 소팅
    if sort == "서울전체":
        pass
    else:
        board_list = board_list.filter(Q(gu__contains=sort))

    # 카테고리에 맞게 소팅
    if sort2 == "분류없음":
        pass
    else:
        board_list = board_list.filter(Q(category__contains=sort2))

    # 조회된 목록을 기준으로 검색 조건을 줘서 필터링
    # Q() : OR 조건으로 데이터를 조회
    # subject__contains(대소문자 구별)
    # subject__icontains(대소문자 구별 하지 않음)

    if keyword:
        board_list = board_list.filter(
            Q(subject__icontains=keyword)
            | Q(content__icontains=keyword)
            | Q(nickname__nickname__icontains=keyword)
            | Q(answer__nickname__nickname__icontains=keyword)
        ).distinct()

    paginator = Paginator(
        board_list, 10
    )  # Paginator 객체 생성(전체목록, 10) : 전체목록에서 10개씩 가져오기
    page_obj = paginator.get_page(page)

    context = {
        "board_list": page_obj,
        "page": page,
        "keyword": keyword,
        "sort": sort,
        "sort_a": sort_a,
        "sort2": sort2,
    }

    return render(request, "board/board_list.html", context)


# 게시판 상세페이지
def detail(request, board_id):

    ### 페이지 나누기 추가
    page = request.GET.get("page", 1)  # http://127.0.0.1:8000/board/?page=1
    keyword = request.GET.get("keyword", "")
    sort = request.GET.get("sort", "")
    sort_a = request.GET.get("sort_a", "")

    # 없는 id를 요청했을 때 웹 페이지에 오류 메세지가 그대로 출력
    board = get_object_or_404(Board, id=board_id)

    ### 조회수 추가
    # 사용자 ip 가져오기
    ip = get_client_ip(request)

    # 찾은 ip가 BoardCount 테이블에 있는지 확인
    cnt = BoardCount.objects.filter(ip=ip, board=board).count()

    if cnt == 0:  # 조회수 증가
        # 모델 생성
        bc = BoardCount(ip=ip, board=board)
        # 저장
        bc.save()
        # question 테이블의 view_cnt 1 증가
        if board.view_cnt:
            board.view_cnt += 1
        else:
            board.view_cnt = 1
        board.save()
    context = {
        "board": board,
        "page": page,
        "keyword": keyword,
        "sort": sort,
        "sort_a": sort_a,
    }
    return render(request, "board/board_detail.html", context)

companion_animals/board/views/board_views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from common.models import Profile
from ..models import Board
from ..forms import BoardForm

# 게시글 등록
@login_required(login_url="common:login")
def board_create(request):

    if request.method == "POST":
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.create_date = timezone.now()
            # 작성자 추가(현재 로그인 사용자 : "request.user")
            profile = Profile.objects.get(user_id=request.user)
            board.nickname = profile
            board.save()
            return redirect("board:index")

    else:
        form = BoardForm()

    return render(request, "board/board_form.html", {"form": form})


# 게시글 수정(원본 내용 보여준 후 수정)
@login_required(login_url="common:login")
def board_modify(request, board_id):

    # board_id 값에 맞는 질문 찾아오기
    board = get_object_or_404(Board, pk=board_id)

    if request.user.id == board.nickname:
        messages.error(request, "수정할 권한이 없습니다.")
        return redirect("board:detail", board_id=board_id)

    if request.method == "POST":
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save(commit=False)
            profile = Profile.objects.get(user_id=request.user)
            board.nickname = profile
            board.modify_date = timezone.now()
            board.save()

            return redirect("board:detail", board_id=board_id)
    else:
        form = BoardForm(instance=board)

    return render(request, "board/board_form.html", {"form": form})


# 게시글 삭제
@login_required(login_url="common:login")
def board_delete(request, board_id):

    # board_id 질문 찾아오기
    board = get_object_or_404(Board, pk=board_id)

    if request.user.id == board.nickname:
        messages.error(request, "삭제할 권한이 없습니다.")
        return redirect("board:detail", board_id=board_id)

    # 삭제
    board.delete()

    return redirect("board:index")

companion_animals/board/views/comment_views.py
from django.shortcuts import redirect, render, get_object_or_404, resolve_url
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from common.models import Profile

from ..models import Answer, Comment
from ..forms import CommentForm

# 대댓글 등록
@login_required(login_url="common:login")
def comment_create(request, answer_id):

    # 질문 가져오기 - models.py에서 질문 정로를 question에서 담아서 옴
    answer = get_object_or_404(Answer, pk=answer_id)

    if request.method == "POST":
        form = CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            # 추가 작업 (forms.py에서 안한 작업)
            profile = Profile.objects.get(user_id=request.user)
            comment.nickname = profile
            comment.create_date = timezone.now()  # 현재 시간 날짜
            comment.answer = answer
            comment.save()

            # 앵커가 들어온 후
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:detail", comment.answer.board.id), comment.id
                )
            )

    else:
        form = CommentForm()

    return render(request, "board/comment_form.html", {"form": form})


# 대댓글 수정
@login_required(login_url="common:login")
def comment_modify(request, comment_id):

    comment = get_object_or_404(Comment, pk=comment_id)

    # 작성자와 같은지 확인
    if request.user.id == comment.nickname:
        messages.error(request, "댓글을 수정할 권한이 없습니다.")
        return redirect("board:detail", board_id=comment.answer.board.id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()

            # 앵커가 들어온 후
            return redirect(
                "{}#comment_{}".format(
                    resolve_url("board:detail", board_id=comment.answer.board.id),
                    comment.id,
                )
            )
    else:
        form = CommentForm(instance=comment)

    return render(request, "board/comment_form.html", {"form": form})


# 대댓글 삭제
@login_required(login_url="common:login")
def comment_delete(request, comment_id):
    # 삭제할 데이터 찾기
    comment = get_object_or_404(Comment, pk=comment_id)

    # 작성자와 같은지 확인
    if request.user.id == comment.nickname:
        messages.error(request, "댓글을 삭제할 권한이 없습니다.")
        return redirect("board:detail", question_id=comment.answer.board.id)

    # 댓글 삭제 명령어
    comment.delete()

    # 내용보기로 들어가기
    return redirect("board:detail", question_id=comment.answer.board.id)

companion_animals/board/views/vote_views.py
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from ..models import Board


# 게시물 추천 등록
@login_required(login_url="common:login")
def vote_board(request, board_id):
    # board_id 해당하는 게시물 가져오기
    board = get_object_or_404(Board, pk=board_id)
    # 자신의 글은 추천 불가 로그인 사용자 == 질문작성자
    if request.user.id == board.nickname.user_id:
        messages.error(request, "본인이 작성한 글은 추천할 수 없습니다.")
    else:
        # board.voter + 1
        board.voter.add(request.user)
    return redirect("board:detail", board_id=board_id)

companion_animals/templates/board/answer_form.html
{% extends 'base.html' %} {% block content %}
<div class="container my-3">
  <form action="" method="post" class="post-form my-3">
    {% csrf_token %} {% include 'form_errors.html' %}
    <!-- 답변 수정 폼 -->
    <div class="form-group">
      <label for="content">댓글 내용</label>
      <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value | default_if_none:''}}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">댓글 등록</button>
  </form>
</div>
{% endblock content %}

companion_animals/templates/board/board_detail.html
{% extends 'base.html' %} {% load board_filter %} {% block content %}
<div class="container my-3">
  <!--추천 오류 표시-->
  {% if messages %}
  <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
    <strong> {{message.tags}} </strong>
    <ul>
      <li>{{message.message}}</li>
    </ul>
    {% endfor %}
  </div>
  {% endif %}
  <h2 class="border-bottom py-2">
    <!-- 질문 제목-->
    {{board.subject}}
  </h2>
  <div class="row my-3">
    <!--추천영역-->
    <div class="col-1">
      <div class="bg-light text-center p-3 border font-weight-bolder mb-1">
        <!--추천 수-->
        {{board.voter.count}}
      </div>
      <a href="#" data-uri="{% url 'board:vote_board' board.id %}" class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
    </div>
    <!--추천영역 종료-->
    <div class="col-11">
      <div class="card">
        <div class="card-body">
          <div class="card-text">
            <!--질문 내용-->
            {{board.content|mark}}
          </div>
          <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2 text-left">
              <!--작성자-->
              <div class="mb-2">닉네임 : {{board.nickname.nickname}}</div>
              <!--질문 작성 날짜-->
              {{board.create_date}}
            </div>
          </div>
          {% if board.modify_date %}
          <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2 text-left">
              <div class="mb-2">modified at</div>
              <!--질문 수정 날짜-->
              {{board.modify_date}}
            </div>
          </div>
          {% endif %} {% if board.nickname.user_id == request.user.id %}
          <div class="my-3">
            <a href=" {% url 'board:board_modify' board.id %}  " class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" data-uri="{% url 'board:board_delete' board.id %}" class="delete btn btn-sm btn-outline-secondary">삭제</a>
          </div>
          {% endif %}
          <!-- 질문 댓글 영역 end -->
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-1"></div>
    <div class="col-11">
      <!-- 변수 넘기기 ?keyword={{keyword}}&page={{page}}&sort={{sort}} -->
      <a href="javascript:void(0);" class="back_to_list btn btn-sm my-4" style="background-color: #234e70; color: white"><i class="fas fa-list"> 목록으로</i></a>
    </div>
  </div>
  <h5 class="border-bottom my-3 py-2">
    <!--답변 개수-->
    {{board.answer_set.count}} 개의 답변이 있습니다.
  </h5>
  {% for answer in board.answer_set.all %}
  <a name="answer_{{answer.id}}"></a>
  <div class="row my-3">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <div class="card-text">
            <!--답변 내용-->
            {{answer.content|mark}}
          </div>
          <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2 text-left">
              <!--작성자-->
              <div class="mb-2">닉네임 : {{answer.nickname.nickname}}</div>
              <!--답변 작성 날짜-->
              {{ answer.create_date }}
            </div>
          </div>
          {% if answer.modify_date %}
          <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2 text-left">
              <div class="mb-2">modified at</div>
              <!--답변 수정 날짜-->
              {{answer.modify_date}}
            </div>
          </div>
          {% endif %} {% if request.user.id == answer.nickname.user_id %}
          <div class="my-3">
            <a href=" {% url 'board:answer_modify' answer.id %} " class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="#" data-uri=" {% url 'board:answer_delete' answer.id %} " class="delete btn btn-sm btn-outline-secondary">삭제</a>
          </div>
          {% endif %}
          <!--답변 댓글 작성부분-->
          <!-- 답변 댓글 영역 start -->
          {% if answer.comment_set.count > 0 %}
          <div class="mt-3">
            {% for comment in answer.comment_set.all %}
            <!-- 답변 댓글 앵커 부분-->
            <a name="comment_{{comment.id}}"></a>
            <div class="comment py-2 text-muted">
              <span style="white-space: pre-line">{{comment.content}}</span>
              <span> - 닉네임 : {{comment.nickname.nickname}} // {{comment.create_date}} {% if comment.modify_date %} (수정 : {{comment.modify_date}} ) {% endif %} </span>
              <!--  로그인 사용자 == 작성자 -->
              {% if request.user.id == comment.nickname.user_id %}
              <a href="{% url 'board:comment_modify' comment.id %}" class="small">수정</a>
              <a href="#" data-uri="{% url 'board:comment_delete' comment.id %}" class="delete small">삭제</a>
              {% endif %}
            </div>
            {% endfor %}
          </div>
          {% endif %}
          <div>
            <a href="{% url 'board:comment_create' answer.id %} " class="small" style="color: #234e70">답변 댓글 추가...</a>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  <form action=" {% url 'board:answer_create' board.id %} " method="post" class="my-3">
    {% csrf_token %}
    <!--오류표시-->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field in form %} {% if field.errors %}
      <strong> {{field.label}} </strong>
      {{field.errors}} {% endif %} {% endfor %}
    </div>
    {% endif %}
    <div class="form-group">
      <textarea name="content" id="content" rows="10" class="form-control" {% if not user.is_authenticated %}disabled{% endif %}></textarea>
    </div>
    <input type="submit" value="답변 등록" class="btn" style="background-color: #234e70; color: white" />
  </form>
</div>
<!-- 페이지 나누기 추가 -->
<form action="{% url 'board:index' %}" id="searchForm" method="get">
  <input type="hidden" name="keyword" id="keyword" value="{{keyword|default_if_none:''}}" />
  <input type="hidden" name="page" id="page" value="{{page}}" />
  <input type="hidden" name="sort" id="sort" value="{{sort}}" />
</form>
{% endblock %} {% block script %}
<script>
  $(function () {
    $(".delete").click(function () {
      //console.log($(this).data("uri"))
      if (confirm("정말로 삭제하시겠습니까?")) {
        location.href = $(this).data("uri");
      }
    });

    // 추천 버튼 클릭시 data-uri 값 가져오기
    $(".recommend").click(function () {
      //console.log($(this).data("uri"));
      if (confirm("정말로 추천하시겠습니까?")) {
        location.href = $(this).data("uri");
      }
    });

    // 목록으로 버튼 클릭시 searchForm 보내기
    $(".back_to_list").click(function (e) {
      $("#searchForm").submit();
    });
  });
</script>
{% endblock %}

<!--
  request.user : 현재 로그인된 정보(User 객체)

  is_authenticated => 현재 로그인되어 있는 객체를 의미
-->

companion_animals/templates/board/board_main.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container" style="padding-left: 5%">
  <img src="{% static 'img/title.png' %}" alt="image" />
</div>

<div class="container" style="padding-left: 5%">
  <a href="{% url 'board:index' %}" style="font-size: 35px; text-align: center; color: #234e70; text-decoration: underline double">게시판으로 이동하기 >>> </a>
</div>
{% endblock %}

companion_animals/templates/board/comment_form.html
{% extends 'base.html' %} {% block content %}
<div class="container my-3">
  <h5 class="my-3 border-bottom pb-2">답변</h5>
  <form action="" method="post" class="post-form my-3">
    {% csrf_token %} {% include 'form_errors.html' %}
    <!-- 대댓글 폼 -->
    <div class="form-group">
      <label for="content">답변 내용</label>
      <textarea name="content" id="content" rows="10" class="form-control">{{form.content.value | default_if_none:''}}</textarea>
    </div>
    <button type="submit" class="btn btn-primary">등록</button>
  </form>
</div>

{% endblock content %}