companion_animals/chat/urls.py
# chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path("index", views.index, name="index"),
    path("create/", views.create, name="create"),
    path("<int:room_pk>/", views.enter_room, name="room"),
]

companion_animals/common/urls.py
from xml.etree.ElementInclude import include
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "common"

urlpatterns = [
    # django.contrib.auth 에서 제공하는 LoginView
    # 클래스를 활용하기 때문에 별도의 views 는 작성하지 않음
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", views.signup, name="signup"),
    path("profile/", views.profile, name="profile"),
    path("member_del/", views.delete, name="delete"),
    path("change_password/", views.change_password, name="change_password"),
    # 비밀번호 초기화
    path(
        "password_reset/",
        views.PasswordResetView.as_view(template_name="common/password_reset.html"),
        name="password_reset",
    ),
    path(
        "password_reset_done/",
        views.PasswordResetDoneView.as_view(
            template_name="common/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset_confirm/<uidb64>/<token>/",
        views.PasswordResetConfirmView.as_view(
            template_name="common/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
]

companion_animals/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from petmap import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("board/", include("board.urls")),
    path("common/", include("common.urls")),
    path("petmap/", include("petmap.urls")),
    path("chat/", include("chat.urls")),
    # 메인화면
    path("", views.main, name="main"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

companion_animals/common/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from PIL import Image

# User 객체 하나와 매칭되는 Profile
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    # 별명
    nickname = models.CharField(max_length=30, default="익명의 집사")
    # 연락처
    phone = models.CharField(max_length=30)
    # 반려동물 종
    species = models.CharField(max_length=30)
    # 반려동물 이름
    pet_name = models.CharField(max_length=30)
    # 이미지
    image = models.ImageField(upload_to="profile/", default="profile/default.png")

    def __str__(self) -> str:
        return f"{self.user.username} Profile"

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)
        img = Image.open(self.image.path)

        # 이미지 리사이징
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_profile(sender, instance, **kwargs):
    instance.profile.save()

companion_animals/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")


class UserUpdateForm(forms.ModelForm):
    username = forms.CharField(
        label="사용자이름", widget=forms.TextInput(attrs={"readonly": "readonly"})
    )
    email = forms.EmailField(
        label="이메일", widget=forms.EmailInput(attrs={"readonly": "readonly"})
    )

    class Meta:
        model = User
        fields = ("username", "email")


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("nickname", "phone", "species", "pet_name", "image")

        # 에러 메세지가 보여질 때 라벨명이 field명을 이용하기 때문에
        # 영어로 나오는 부분을 원하는 한글로 변경
        labels = {
            "nickname": "별명",
            "phone": "핸드폰번호",
            "species": "반려동물 종류",
            "pet_name": "반려동물 이름",
            "image": "사진",
        }


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("nickname", "phone", "species", "pet_name", "image")
        labels = {
            "nickname": "별명",
            "phone": "핸드폰번호",
            "species": "반려동물 종류",
            "pet_name": "반려동물 이름",
            "image": "사진",
        }


# from django.core.exceptions import ValidationError
# import django.contrib.auth.forms as auth_forms
# from django.contrib.auth.models import User


# class PasswordResetForm(auth_forms.PasswordResetForm):
#     username = auth_forms.UsernameField(label="사용자ID")  # CharField 대신 사용

#     # validation 절차:
#     # 1. username에 대응하는 User 인스턴스의 존재성 확인
#     # 2. username에 대응하는 email과 입력받은 email이 동일한지 확인

#     def clean_username(self):
#         data = self.cleaned_data["username"]
#         if not User.objects.filter(username=data).exists():
#             raise ValidationError("해당 사용자ID가 존재하지 않습니다.")

#         return data

#     def clean(self):
#         cleaned_data = super().clean()
#         username = cleaned_data.get("username")
#         email = cleaned_data.get("email")

#         if username and email:
#             if User.objects.get(username=username).email != email:
#                 raise ValidationError("사용자의 이메일 주소가 일치하지 않습니다")

#     def get_users(self, email=""):
#         active_users = User.objects.filter(
#             **{
#                 "username__iexact": self.cleaned_data["username"],
#                 "is_active": True,
#             }
#         )
#         return (u for u in active_users if u.has_usable_password())

companion_animals/common/views.py
from django.contrib import messages
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages, auth
from django.views.decorators.http import require_POST
from requests import Session, session


from .models import Profile
from .forms import UserForm, ProfileUpdateForm, ProfileForm, UserUpdateForm


def signup(request):
    """
    회원가입
    """
    if request.method == "POST":
        # 사용자가 입력한 폼 가져오기
        form = UserForm(request.POST)
        if form.is_valid():
            # db 반영
            form.save()
            # 로그인 페이지를 보여줄 때
            # return redirect('common:login')

            # form.cleaned_data.get() : 넘어온 폼에서 화면의 입력 값을 얻기 위한 함수
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")

            # authenticate() : 사용자 아이디와 비밀번호를 담아서 자격증명을 요청하는 함수
            user = authenticate(username=username, password=raw_password)

            if user is not None:
                # login() : 로그인 해주는 함수
                login(request, user)

            # messages.success(request, f"Paws & Tails의 가족이 되신 걸 환영합니다!")
            return redirect("board:index")

    else:
        form = UserForm()

    return render(request, "common/signup.html", {"form": form})


@login_required
def profile(request):
    profile = Profile.objects.get(user_id=request.user)
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile
        )
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            # messages.success(request, f"계정이 업데이트 되었습니다!")
            return redirect("main")  # Redirect back to profile page

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {"u_form": u_form, "p_form": p_form, "profile": profile}

    return render(request, "common/profile.html", context)


def delete(request):
    if request.method == "POST":
        if request.user.is_authenticated:
            request.user.delete()
            request.session.clear()
            return redirect("main")
    return render(request, "common/member_del.html")


@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            request.session.clear()
            # messages.success(request, "Your password was successfully updated!")
            return redirect("main")
        else:
            pass
    else:
        form = PasswordChangeForm(request.user)
    return render(request, "common/change_password.html", {"form": form})


from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


class PasswordResetView(auth_views.PasswordResetView):
    """
    비밀번호 초기화 - 사용자ID, email 입력
    """

    template_name = "common/password_reset.html"
    success_url = reverse_lazy("common:password_reset_done")
    email_template_name = "common/password_reset_email.html"


class PasswordResetDoneView(auth_views.PasswordResetDoneView):
    """
    비밀번호 초기화 - 메일 전송 완료
    """

    template_name = "common/password_reset_done.html"


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    """
    비밀번호 초기화 - 새로운 비밀번호 입력
    """

    template_name = "common/password_reset_confirm.html"
    success_url = reverse_lazy("common:login")

companion_animals/templates/common/change_password.html
{% extends 'base.html' %} {% block content %} {% include 'form_errors.html' %}

<h2 style="text-align: center">비밀번호 변경</h2>
{% if error_message %}
<p><strong>{{ error_message }}</strong></p>
{% endif %}
<form method="post" style="text-align: center">
  {% csrf_token %} {{ form }}
  <button type="submit">Save changes</button>
</form>

{% endblock %}

companion_animals/templates/common/login.html
{% extends 'base.html' %} {% block content %}
<div class="container my-3">
  <!-- 회원가입 메뉴 시작-->
  <div class="row">
    <div class="col-4">
      <h4>로그인</h4>
    </div>
    <div class="col-8 text-right">
      <span> 또는 <a href="{% url 'common:signup' %}"> 계정을 만드세요</a> </span>
    </div>
  </div>
  <!-- 회원가입 메뉴 끝-->
  <form action="" method="post" class="post-form">
    {% csrf_token %} {% include 'form_errors.html' %}
    <div class="form-group">
      <label for="username">사용자 ID</label>
      <input type="text" name="username" id="username" class="form-control" value="{{ form.username.value | default_if_none:'' }}" />
    </div>
    <div class="form-group">
      <label for="password">비밀번호</label>
      <input type="password" name="password" id="password" class="form-control" value="{{ form.password.value | default_if_none:'' }}" />
    </div>
    <div>
      <button type="submit" class="btn btn-primary">로그인</button>
    </div>
    <div>
      <a type="button" href="{% url 'common:password_reset' %}">비밀번호찾기</a>
    </div>
  </form>
</div>
{% endblock %}

companion_animals/templates/common/member_del.html
{% extends 'base.html' %} {% block content %}
<div class="m-5">
  <h1 class="mb-5">회원탈퇴</h1>
  <form action="{% url 'common:delete' %}" method="post">
    {% csrf_token %} 비밀번호 : <input type="password" name="password" />
    <input type="submit" value="회원탈퇴" />
  </form>
</div>
{% endblock %}

companion_animals/templates/common/password_reset.html
{% extends "base.html" %} {% block content %}
<div class="container my-3">
  <h4 class="border-bottom pb-2 my-3">비밀번호 찾기</h4>

  <form method="post" class="post-form" action="{% url 'common:password_reset' %}">
    <!-- action 속성은 생략 가능 -->
    {% csrf_token %} {% include "form_errors.html" %}
    <div class="form-group">
      <label for="username">사용자ID</label>
      <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}" />
    </div>
    <div class="form-group">
      <label for="email">등록한 이메일</label>
      <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}" />
    </div>
    <button type="submit" class="btn btn-primary">이메일 전송</button>
  </form>
</div>
{% endblock %}

companion_animals/templates/common/password_reset_confirm.html
{% extends "base.html" %} {% block content %}
<div class="container my-3">
  <h4 class="border-bottom pb-2 my-3">비밀번호 초기화</h4>

  {% if validlink %}
  <form method="post" class="post-form">
    <!-- password_reset_confirm으로 action할 필요 없음 -->
    {% csrf_token %} {% include "form_errors.html" %}
    <div class="form-group">
      <label for="new_password1">새로운 비밀번호</label>
      <input type="password" class="form-control" name="new_password1" id="new_password1" />
    </div>
    <div class="form-group">
      <label for="new_password2">비밀번호 확인</label>
      <input type="password" class="form-control" name="new_password2" id="new_password2" />
    </div>
    <button type="submit" class="btn btn-primary">변경하기</button>
  </form>
  {% else %}
  <p>링크가 유효하지 않습니다.</p>
  {% endif %}
</div>
{% endblock %}

companion_animals/templates/common/password_reset_done.html
{% extends "base.html" %} {% block content %}
<div class="container my-3">
  <h4 class="border-bottom pb-2 my-3">이메일 전송 완료</h4>

  <a href="{% url 'common:login' %}" class="btn btn-primary">처음으로</a>
</div>
{% endblock %}

companion_animals/templates/common/password_reset_email.html
아래 링크 클릭해주세요 !!! </br>
{{ protocol }}://{{ domain }}{% url 'common:password_reset_confirm' uidb64=uid token=token %}

companion_animals/templates/common/profile.html
{% extends 'base.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="content-section">
  <div class="media">
    <div class="row ml-5 mt-3 mb-3">
      <img class="rounded account-img" src="{{profile.image.url}}" style="border: solid" alt="반려동물" />
    </div>
    <div class="media-body m-5">
      <!-- FORM HERE -->
      <form method="POST" enctype="multipart/form-data" class="mb-5 mr-5 ml-5">
        {% csrf_token %}
        <fieldset class="form-group">
          <legend class="border-bottom mb-4">프로필 정보</legend>
          {{ u_form|crispy }}
          <!-- User form -->
          {{ p_form|crispy }}
          <!-- Profile form -->
        </fieldset>
        <div class="form-group">
          <button class="btn" type="submit" style="background-color: #234e70; color: white">수정하기</button>
          <a class="btn" type="button" style="background-color: orange; color: white" href="{% url 'common:change_password' %}">비밀번호 변경</a>
          <a class="btn" type="button" style="background-color: blue; color: white" href="{% url 'common:delete' %}">탈퇴하기</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

companion_animals/templates/common/signup.html
{% extends 'base.html' %} {% block content %}
<div class="container my-3">
  <!-- 회원가입 메뉴 시작-->
  <div class="row">
    <div class="col-4">
      <h4>회원가입</h4>
    </div>
    <div class="col-8 text-right">
      <span> 또는 <a href="{% url 'common:login' %}"> 로그인하기</a> </span>
    </div>
  </div>
  <!-- 회원가입 메뉴 끝-->
  <form action="" method="post" class="post-form">
    {% csrf_token %} {% include 'form_errors.html' %}
    <div class="form-group">
      <label for="username">사용자 ID</label>
      <input type="text" name="username" id="username" class="form-control" value="{{ form.username.value | default_if_none:'' }}" />
    </div>
    <div class="form-group">
      <label for="password1">비밀번호</label>
      <input type="password" name="password1" id="password1" class="form-control" value="{{ form.password1.value | default_if_none:'' }}" />
    </div>
    <div class="form-group">
      <label for="password2">비밀번호 확인</label>
      <input type="password" name="password2" id="password2" class="form-control" value="{{ form.password2.value | default_if_none:'' }}" />
    </div>
    <div class="form-group">
      <label for="email">이메일</label>
      <input type="text" name="email" id="email" class="form-control" value="{{ form.email.value | default_if_none:'' }}" />
    </div>
    {% comment %}
    <div class="form-group">
      <label for="nickname">닉네임(별명)</label>
      <input type="text" name="nickname" id="nickname" class="form-control" value="{{ form.nickname.value | default_if_none:'익명의 집사' }}" />
    </div>
    <div class="form-group">
      <label for="phone">핸드폰</label>
      <input type="text" name="phone" id="phone" class="form-control" value="{{ form.phone.value | default_if_none:'' }}" />
    </div>
    <div class="form-group">
      <label for="species">반려동물 종</label>
      <input type="text" name="species" id="species" class="form-control" value="{{ form.species.value | default_if_none:'' }}" />
    </div>
    <div class="form-group">
      <label for="pet_name">반려동물 이름</label>
      <input type="text" name="pet_name" id="pet_name" class="form-control" value="{{ form.pet_name.value | default_if_none:'' }}" />
    </div>
    {% endcomment %}
    <div>
      <button type="submit" class="btn btn-primary">회원가입</button>
    </div>
  </form>
</div>
{% endblock content %}